# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            TKVTV
tagline:          取引量No.1！ *当社比
description:      "取引量No.1！ *当社比"
url:              https://takagotch.github.io/page82/
baseurl:          https://takagotch.github.io/page82/
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Karlo Espiritu
  url:            https://facebook.com/takagotch

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/takagotch/page82


